import type { LegalDocumentContent } from './legalTypes';

export const privacyContent: LegalDocumentContent = {
  title: 'SkuadUp Privacy Policy',
  lastUpdated: 'May 9, 2026',
  intro: [
    'This Privacy Policy describes how SkuadUp, Inc., a Delaware corporation doing business as SkuadUp ("SkuadUp," "we," "us," or "our"), collects, uses, discloses, and retains personal information when you use the SkuadUp mobile application, website, APIs, messaging, notifications, content, and related services (collectively, the "Service").',
    'By using the Service, you acknowledge that you have read this Privacy Policy. If you do not agree, please do not use the Service.'
  ],
  sections: [
    { id: 'scope', title: '1. Scope', paragraphs: ['This Privacy Policy applies to information we collect from or about users of the Service, including through account registration, profile creation, game and team participation, messaging, notifications, approximate location and discovery features, customer support, analytics, safety tools, and interactions with our systems and service providers. It does not apply to third-party websites, services, app stores, or integrations that have their own privacy policies.'] },
    { id: 'information-we-collect', title: '2. Information We Collect', paragraphs: ['The categories below describe information we may collect, depending on how you use the Service and your device or app settings.', 'Account and profile information: Name, username, email, phone number, date of birth or age range, profile photo, bio, sports interests, region, preferences. Primary sources: You; authentication providers; app stores.', 'User content and communications: Team names, team photos, game details, event information, direct messages, group or team chat messages, message requests, support messages, reports, photos, and other content you choose to provide. Primary sources: You; other users; support and moderation tools.', 'Activity and usage information: Teams and games you create or join, invitations, approvals, declines, notifications, message activity, moderation actions, blocks, mutes, reports, search, discovery interactions, and feature usage. Primary sources: Your use of the Service; our systems.', 'Location information: Approximate coordinates or a location-derived discovery area that may be offset or generalized by approximately 8 miles, IP-derived general location, and location settings. We do not intentionally display precise real-time location to other users. Primary sources: Your device permissions; IP address; app settings.', 'Device, diagnostics, and analytics: Device identifiers, operating system, app version, language, time zone, IP address, log data, crash data, diagnostic data, analytics events, push tokens, and security signals. Primary sources: Your device; analytics, hosting, and security providers.', 'Future payment or transaction information: The Service is currently free and does not currently offer paid subscriptions, event fees, or in-app purchases. If paid features are added later, we may collect purchase status, app-store transaction identifiers, receipts, refund status, and limited payment metadata. Primary sources: App stores; payment processors; you, if paid features are introduced later.', 'Information from others: Reports about your account or conduct, invitations, team membership, game participation, user-generated references to you, and service-provider information. Primary sources: Other users; vendors; partners; public or permitted sources.'] },
    { id: 'sensitive-information', title: '3. Sensitive Information', paragraphs: ['Depending on how you use the Service, some information may be considered sensitive under certain laws, such as precise geolocation, account credentials, or content that reveals health, injury, disability, or similar information if you choose to provide it. SkuadUp is designed for adults only and is not intended for anyone under 18. We ask that you not submit sensitive information unless it is necessary for the feature you are using. Where required by law, we will obtain consent before collecting or using sensitive information.'] },
    { id: 'how-we-use-information', title: '4. How We Use Information', bullets: ['provide, maintain, secure, debug, and improve the Service;', 'create and manage accounts, profiles, teams, games, chats, message requests, and notifications;', 'facilitate player discovery, team and game coordination, messaging, support, and safety features;', 'personalize content, search, recommendations, location-based discovery, and notifications;', 'authenticate users, prevent account misuse, and protect the Service;', 'detect, investigate, prevent, and respond to spam, abuse, fraud, harassment, threats, safety incidents, unauthorized access, and unlawful activity;', 'moderate content and enforce our Terms of Service, Community Guidelines, and other policies;', 'provide customer support and respond to requests;', 'analyze usage trends, measure feature performance, fix bugs, and develop new features;', 'send administrative, transactional, security, legal, support, and service-related communications;', 'maintain records for any future paid features if introduced, but the Service is currently free and does not currently offer paid subscriptions, event fees, or in-app purchases;', 'comply with legal obligations and protect rights, safety, security, and property; and', 'create aggregated, de-identified, or anonymized information that does not reasonably identify you.'] },
    { id: 'how-we-disclose-information', title: '5. How We Disclose Information', paragraphs: ['We may disclose information in the following circumstances:', 'With other users: profile information, usernames, avatars, team participation, game participation, approximate discovery information, message content, and content you choose to share may be visible to other users depending on your settings and the feature context.', 'With organizers, captains, coaches, admins, or team/game managers: if you interact with a team, game, event, or request, relevant administrators may view information needed to manage participation, safety, moderation, scheduling, and communications.', 'With service providers: vendors may process information for hosting, cloud infrastructure, storage, analytics, crash reporting, security, authentication, approximate location/discovery functionality, push notifications, email delivery, SMS/communications, customer support, and app operations, including Microsoft Azure, Firebase/FCM, Twilio, and SendGrid.', 'For legal, compliance, and safety reasons: we may disclose information if we believe disclosure is reasonably necessary to comply with law or legal process; enforce our policies; investigate misconduct; protect users, SkuadUp, vendors, partners, or others; prevent harm; or respond to emergencies.', 'In business transfers: we may disclose or transfer information in connection with a merger, acquisition, financing, reorganization, bankruptcy, sale of assets, change of control, or similar transaction.', 'With your direction or consent: we may disclose information when you direct us to do so or otherwise consent.'] },
    { id: 'messaging-requests', title: '6. Messaging, Requests, Notifications, and Activity Feeds', paragraphs: ['The Service may support direct messages, group or team chat, message requests, game requests, team requests, activity feeds, badges, push notifications, in-app notifications, and news items. Information related to these features may include message content, timestamps, participants, delivery metadata, read or interaction status, request status, deletion or moderation state, notification preferences, device tokens, and related logs.', 'Even if a message, request, notification, or item is deleted from view, we may retain records for backup, safety, moderation, security, fraud prevention, dispute resolution, analytics, debugging, legal compliance, and enforcement purposes.'] },
    { id: 'approximate-location', title: '7. Approximate Location and Discovery Features', paragraphs: ['If you enable location-based features, the Service is designed to collect and use approximate location information or a location-derived discovery area, not to display your precise real-time location to other users. Current discovery design uses approximate coordinates that are offset or generalized by approximately 8 miles to help nearby users discover players, teams, and games while reducing precise-location exposure.', 'Location-based discovery may be used to surface nearby games, teams, players, or recommendations. The Service is not intended for emergency response, precise tracking, safety monitoring, or attendance verification. You can manage device-level location permissions through your mobile operating system and any in-app settings we provide.'] },
    { id: 'retention', title: '8. Retention', paragraphs: ['We retain information for as long as reasonably necessary for the purposes described in this Privacy Policy, including to provide the Service, maintain business and legal records, enforce policies, resolve disputes, protect safety and security, prevent fraud and abuse, and comply with legal obligations. Approximate location/discovery data is retained only as reasonably necessary for discovery, safety, security, abuse prevention, debugging, and legal purposes, subject to our technical systems and backup cycles.', 'Examples: account profile information is generally retained while your account is active; messages and user content may be retained while needed for delivery, display, safety, moderation, backups, dispute resolution, and legal compliance; logs and diagnostic data may be retained for security, debugging, analytics, and abuse prevention; and de-identified or aggregated information may be retained without identifying you.'] },
    { id: 'choices-controls', title: '9. Your Choices and Controls', bullets: ['update certain account and profile information in the Service;', 'manage notification settings in the Service and through your device settings;', 'manage location permissions through your device settings and available in-app controls;', 'block, mute, report, or restrict certain interactions where supported;', 'delete certain content where the feature allows deletion;', 'request account deletion, subject to permitted retention for legal, operational, safety, security, fraud-prevention, audit, and dispute-resolution purposes; and', 'exercise privacy rights available under applicable law by contacting us.'] },
    { id: 'state-privacy-rights', title: '10. State Privacy Rights', paragraphs: ['Depending on where you live and whether a particular law applies to SkuadUp, you may have rights to access, confirm, correct, delete, obtain a copy of, or appeal decisions regarding your personal information, and to opt out of certain processing such as targeted advertising, sale of personal information, or profiling that produces legal or similarly significant effects. We will process applicable requests in accordance with applicable law after taking reasonable steps to verify your identity.', 'We do not sell personal information for money. Some analytics, advertising, or measurement activities may be considered a "sale," "sharing," or targeted advertising under certain state privacy laws. If we use those activities, we will provide required notices and opt-out mechanisms. Beginning when required by applicable law, we will honor applicable universal opt-out signals where legally required and technically feasible.'] },
    { id: 'children-teens', title: '11. Children and Teens', paragraphs: ['The Service is intended for adults 18 and older. We do not knowingly collect personal information from anyone under 18 through the Service. If you believe a person under 18 has created an account or provided information, contact us so we can investigate and take appropriate action, which may include suspending or deleting the account subject to our legal, safety, security, backup, and dispute-resolution retention needs.'] },
    { id: 'security', title: '12. Security', paragraphs: ['We use reasonable administrative, technical, and organizational measures designed to protect information. However, no method of transmission over the internet or method of storage is completely secure, and we cannot guarantee absolute security. You are responsible for maintaining the security of your account credentials and devices.'] },
    { id: 'international-users', title: '13. International Users', paragraphs: ['SkuadUp is operated from the United States. If you access the Service from outside the United States, your information may be processed in the United States or other countries where privacy laws may differ from those in your location. Where required, we will use appropriate safeguards for cross-border transfers.'] },
    { id: 'third-party-services', title: '14. Third-Party Services', paragraphs: ['The Service may integrate with or rely on third-party services such as Microsoft Azure, Firebase/FCM, Twilio, SendGrid, app stores, authentication providers, mapping/location technologies, analytics, crash reporting, customer support tools, or websites. Those third parties may collect or process information under their own privacy policies.'] },
    { id: 'do-not-track', title: '15. Do Not Track', paragraphs: ['Some browsers transmit "Do Not Track" signals. There is no uniform industry standard for responding to these signals, and we do not currently respond to them. We will honor legally required opt-out preference signals where applicable.'] },
    { id: 'changes-privacy-policy', title: '16. Changes to This Privacy Policy', paragraphs: ['We may update this Privacy Policy from time to time. If we make material changes, we may notify you by updating the effective date, posting the revised version in the Service, sending notice, or providing other notice as appropriate. Your continued use of the Service after an update becomes effective means the updated Privacy Policy will apply.'] },
    { id: 'contact-us', title: '17. Contact Us', paragraphs: ['If you have questions about this Privacy Policy or would like to make a privacy request, contact us at:', 'SkuadUp, Inc.', 'A Delaware corporation', '[MAILING ADDRESS]', 'support@skuadup.com', 'https://skuadup.com'] }
  ]
};
